Updated scaffold files.

diff --git a/.ahoy.yml b/.ahoy.yml
--- a/.ahoy.yml
+++ b/.ahoy.yml
@@ -8,8 +8,8 @@ commands:
     cmd: |
       ahoy clean
       (docker network prune -f > /dev/null && docker network inspect amazeeio-network > /dev/null || docker network create amazeeio-network)
-      ahoy up -- --build --force-recreate   
-      docker cp -L . "$(docker-compose ps -q cli)":/app/ || true
+      ahoy up -- --build --force-recreate
+      docker cp -L . "$(docker compose ps -q cli)":/app/ || true
       ahoy install-site
       ahoy info 1
 
@@ -21,7 +21,7 @@ commands:
       echo "  Site local URL           : " $(ahoy cli echo \$LOCALDEV_URL)
       echo "  Path to project          : " $(ahoy cli echo /app)
       echo "  Path to web root         : " $(ahoy cli echo /app/build/web)
-      echo "  DB port on host          : " $(docker port $(docker-compose ps -q mariadb) 3306 | cut -d : -f 2)
+      echo "  DB port on host          : " $(docker port $(docker compose ps -q mariadb) 3306 | cut -d : -f 2)
       echo "  Xdebug                   : " $(ahoy cli php -v|grep -q Xdebug && echo "Enabled" || echo "Disabled")
       if [ -n "$1" ]; then
         echo "  One-time login           : " $(ahoy login -- --no-browser)
@@ -31,7 +31,7 @@ commands:
     usage: Open DB in Sequel Ace.
     cmd: |
       uname -a | grep -i -q darwin && mdfind -name 'Sequel Ace'|grep -q "Ace" \
-      && HOST_DB_PORT="$(docker port $(docker-compose ps -q mariadb 2>/dev/null) 3306 2>/dev/null | cut -d : -f 2)" \
+      && HOST_DB_PORT="$(docker port $(docker compose ps -q mariadb 2>/dev/null) 3306 2>/dev/null | cut -d : -f 2)" \
       && open "mysql://drupal:drupal@127.0.0.1:${HOST_DB_PORT}/drupal" -a "Sequel Ace" \
       || echo "Not a supported OS or Sequel Ace is not installed."
 
@@ -41,27 +41,27 @@ commands:
 
   up:
     usage: Build and start Docker containers.
-    cmd: docker-compose up -d "$@" && if docker-compose logs | grep -q "\[Error\]"; then exit 1; fi
+    cmd: docker compose up -d "$@" && if docker compose logs | grep -q "\[Error\]"; then exit 1; fi
 
   down:
     usage: Stop Docker containers and remove container, images, volumes and networks.
-    cmd: if [ -f "docker-compose.yml" ]; then docker-compose down --volumes > /dev/null 2>&1; fi
+    cmd: if [ -f "docker-compose.yml" ]; then docker compose down --volumes > /dev/null 2>&1; fi
 
   start:
     usage: Start existing Docker containers.
-    cmd: docker-compose start "$@"
+    cmd: docker compose start "$@"
 
   stop:
     usage: Stop running Docker containers.
-    cmd: docker-compose stop "$@"
+    cmd: docker compose stop "$@"
 
   restart:
     usage: Restart all stopped and running Docker containers.
-    cmd: docker-compose restart
+    cmd: docker compose restart
 
   logs:
     usage: Show Docker logs.
-    cmd: docker-compose logs "$@"
+    cmd: docker compose logs "$@"
 
   pull:
     usage: Pull latest docker images.
@@ -69,15 +69,15 @@ commands:
 
   cli:
     usage: Start a shell inside CLI container or run a command.
-    cmd: if \[ "${#}" -ne 0 \]; then docker-compose exec -e DRUPAL_VERSION=${DRUPAL_VERSION:-10} -T cli bash -c "$*"; else docker-compose exec cli bash; fi
+    cmd: if \[ "${#}" -ne 0 \]; then docker compose exec -e DRUPAL_VERSION=${DRUPAL_VERSION:-10} -T cli bash -c "$*"; else docker compose exec cli bash; fi
 
   composer:
     usage: Run Composer commands in the CLI service container.
-    cmd: docker-compose exec -T cli composer "$@"
+    cmd: docker compose exec -T cli composer "$@"
 
   drush:
     usage: Run Drush commands in the CLI service container.
-    cmd: docker-compose exec -T cli bash -c "drush -r /app/build/web -l \${LOCALDEV_URL} $*"
+    cmd: docker compose exec -T cli bash -c "drush -r /app/build/web -l \${LOCALDEV_URL} $*"
 
   # ----------------------------------------------------------------------------
   # Application commands.
@@ -94,7 +94,7 @@ commands:
   clean:
     usage: Remove containers and all build files.
     cmd: |
-      ahoy down
+      ahoy down || true
       sleep 5
       chmod -Rf 777 build 2>&1 > /dev/null || true
       rm -rf \
@@ -110,7 +110,9 @@ commands:
   lint:
     usage: Lint code.
     cmd: |
-      ahoy cli "cd /app/build && ./vendor/bin/phpcs --standard=../phpcs.xml" \
+      ahoy cli "cp -Rf phpcs.xml phpstan.neon build > /dev/null" \
+      && ahoy cli "cd /app/build && ./vendor/bin/phpcs" \
+      && ahoy cli "cd /app/build && ./vendor/bin/phpstan" \
       && ahoy cli "cd /app/build && ./vendor/bin/drupal-check --drupal-root=web ../src && cd .." \
       && ahoy cli "cd /app/build && ./vendor/bin/rector process ../src --dry-run && cd .."
 
